"""empty message

Revision ID: 1353e1bce4a8
Revises: 2c9142f125dd
Create Date: 2024-09-27 18:13:46.042777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1353e1bce4a8'
down_revision = '2c9142f125dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.drop_constraint('Product_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Product_category_id_fkey', 'Category', ['category_id'], ['id'])

    # ### end Alembic commands ###
