"""empty message

Revision ID: 7416f5722081
Revises: 96ed9a80c248
Create Date: 2024-09-11 13:28:49.213961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7416f5722081'
down_revision = '96ed9a80c248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('mobile', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('adress', sa.String(length=1000), nullable=False))
        batch_op.create_unique_constraint(None, ['mobile'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('adress')
        batch_op.drop_column('mobile')
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
