"""empty message

Revision ID: ab32c4437f2d
Revises: aa43e9889581
Create Date: 2024-09-26 12:14:01.281664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab32c4437f2d'
down_revision = 'aa43e9889581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocked_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jti', sa.String(length=100), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blocked_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('jti')

    # ### end Alembic commands ###
